version: '3'

services:
  app:
    build: ./
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    # command: sh -c "npm run dev"
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
volumes:
  node_modules:
